name: Build ARMv7 Exploit
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARMv7 cross compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf

      - name: Compile exploit
        run: |
          arm-linux-gnueabihf-gcc cve-2017-11176.c -o exp -pthread -static

      - name: Upload compiled exp
        uses: actions/upload-artifact@v4
        with:
          name: cve-2017-11176-armv7
          path: exp
